In [2]:
import numpy as np

In [3]:
#create arrays using numpy
#create a 1d array

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
arr1.shape

(5,)

In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1, 5) # 1 row 5 cols

array([[1, 2, 3, 4, 5]])

In [9]:
arr2.shape

(5,)

In [10]:
np.arange(0, 10, 2).reshape(5, 1) #(start, stop, step)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [15]:
#numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print(arr1 + arr2)

[11 22 33 44 55]


In [16]:
#element wise substraction
print(arr2 - arr1)

[ 9 18 27 36 45]


In [17]:
#element wise multiplication and division
print(arr1 * arr2)
print(arr2 / arr1)

[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [18]:
#universal functions

arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [19]:
#exponential
print(np.exp(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [21]:
#sine
print(np.sin(arr))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [23]:
#array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
arr[0]

array([1, 2, 3, 4])

In [25]:
arr[0][3]

np.int64(4)

In [26]:
arr[1][2:]

array([7, 8])

In [27]:
arr[2][2:]

array([11, 12])

In [28]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [29]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [31]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [32]:
#modify elements

arr[0, 0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [33]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [34]:
#stastical concepts
#mean and standard deviation

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)

#normalize
normalized_data = (data - mean) / std_dev
print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

5.5
5.5
2.8722813232690143
8.25


In [38]:
#logical operations

data = np.arange(1, 11)

data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [40]:
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [44]:
data[(data > 5) & (data < 8)]

array([6, 7])